# wandb
project_name: dsba_nlp_study
run_name: null
watch_model: true
log_gradients: true
log_freq: 100

# hparams
lr: 5e-5
max_epochs: 5
weight_decay: 0.1

# path
model_name: ${model.model_id}
model_save_path: /workspace/checkpoints/${model.model_id}